{"uuid": "91f003bb-33e7-480c-87c6-1d8aefa72f28", "children": ["05ce58da-c376-4837-a422-ed9a2fbb0568", "558f0d61-93ee-4d52-a82c-9f586e9a5493", "48bd882f-e6a2-4ea3-88e5-a76fec6766bc", "124b73ca-0896-4ee3-af52-46cb915cbbfa", "61e1838b-87ef-4061-b8c5-324681df5bf2", "556e243a-2439-4281-8628-24ecbf1b124c"], "befores": [{"name": "test_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'tests' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"C:\\Users\\Pavan\\AppData\\Local\\Programs\\Python\\Python37-32\\Amazon_Python_Automation\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Pavan\\AppData\\Local\\Programs\\Python\\Python37-32\\Amazon_Python_Automation\\lib\\site-packages\\_pytest\\fixtures.py\", line 935, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Pavan\\AppData\\Local\\Programs\\Python\\Python37-32\\Amazon_Python_Automation\\lib\\site-packages\\_pytest\\fixtures.py\", line 794, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"E:\\Gyan_Matrix\\Amazon_Python_Automation\\conftest.py\", line 15, in test_setup\n    driver = webdriver.Chrome(executable_path=path)\n  File \"C:\\Users\\Pavan\\AppData\\Local\\Programs\\Python\\Python37-32\\Amazon_Python_Automation\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"C:\\Users\\Pavan\\AppData\\Local\\Programs\\Python\\Python37-32\\Amazon_Python_Automation\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1555411429911, "stop": 1555411429913}], "start": 1555411429911, "stop": 1555411431620}